spring:
  application:
    name: myTradingPlatform

  datasource:
    url: jdbc:mysql://localhost:3307/my_trading_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# AngelOne Properties
angelone:
  api-key: ${ANGELONE_API_KEY}
  client-code: ${ANGELONE_CLIENT_CODE}
  password: ${ANGELONE_PASSWORD}
  totp-secret: ${ANGELONE_TOTP_SECRET}

# Upstox Properties
upstox:
  access-token: ${UPSTOX_ACCESS_TOKEN}

# Actuator
management:
  endpoints:
    enabled-by-default: false
  metrics:
    enable:
      all: false